### ISSUE TITLE
Modulo bias in dice rolling function

### ISSUE THREAD

**Issue by hleach** [ThePat02/DiceEngine#1]
In dice_engine.gd:

```
    for die in range(amount):
        dice_results.append(randi() % sides + 1)
```

This introduces modulo bias into the roll causing it to favor lower values in dice sizes that are not a power of two.

Looking over godot's rng implementation, randi_range() will give an equal probability on all values.

For reference: 

https://docs.godotengine.org/en/stable/classes/class_randomnumbergenerator.html#class-randomnumbergenerator-method-randi-range

https://stackoverflow.com/questions/10984974/why-do-people-say-there-is-modulo-bias-when-using-a-random-number-generator

**Comment by ThePat02** [comment]
This is an overlook on my side. Looks like I didn't check the code when refactoring with Copilot. Will fix this later today!

**Comment by ThePat02** [comment]
Fixed it ^^
